import test from 'node:test';
import assert from 'node:assert/strict';
import {MINUTE,dayAt,localTime,shiftDay,validDay,timestamp,checkTask,makeSnapshot,motion,schedule} from '../lib/rules.mjs';
import {notificationPlan,validateSubscription} from '../lib/push.mjs';
import {normalizeRows,matchRows,parseWindow,sheetPlans} from '../lib/sheets.mjs';
import {readPages,getOnfleet} from '../lib/onfleet.mjs';
import {makeSession,authorized,requireAuth,requireOrigin} from '../lib/security.mjs';
import {addSamples} from '../lib/snapshot.mjs';
const day='2026-09-10';const at=(h,m=0)=>localTime(day,h,m);
const pickup=(extra={})=>({id:'pickup1',shortId:'abcd1234',worker:'driver1',state:1,pickupTask:true,completeAfter:at(11),completeBefore:at(11),...extra});
const worker=(extra={})=>({id:'driver1',name:'Test Driver',onDuty:true,timeLastSeen:at(10,15),location:[-79.4,43.7],activeTask:null,...extra});
const check=(t,now=at(10))=>checkTask(t,{now,selectedDate:day});
test('T-61 minutes: scheduled, no Start warning',()=>assert.equal(check(pickup(),at(9,59)).flags.length,0));
test('T-60 minutes: exactly one NOT_STARTED warning',()=>assert.equal(check(pickup(),at(10)).flags.filter(f=>f.kind==='NOT_STARTED').length,1));
test('T-60 not confused with actual pickup late',()=>assert.equal(check(pickup(),at(10)).status,'ACTION_REQUIRED'));
test('T-45 escalates the unstarted warning',()=>assert.equal(check(pickup(),at(10,15)).flags.find(f=>f.kind==='NOT_STARTED').severity,'URGENT'));
test('Started pickup does not get unstarted warning',()=>assert.equal(check(pickup({state:2,eta:1200}),at(10)).flags.some(f=>f.kind==='NOT_STARTED'),false));
test('Starting a different task does not satisfy this pickup',()=>{const s=makeSnapshot({workers:[worker({activeTask:'different'})],tasks:[pickup()],date:day,now:at(10)});assert.equal(s.drivers[0].status,'NOT_STARTED');});
test('Tomorrow task excluded from today even with route delay',()=>{const t=pickup({completeAfter:localTime('2026-09-11',11),completeBefore:localTime('2026-09-11',11),delayTime:900});assert.equal(check(t),null);});
test('Tomorrow assigned task is scheduled, not risk/on-time',()=>{const t=pickup({completeAfter:localTime('2026-09-11',11),completeBefore:localTime('2026-09-11',11),estimatedCompletionTime:localTime('2026-09-11',12)});assert.equal(checkTask(t,{now:at(10),selectedDate:'2026-09-11'}).status,'SCHEDULED');});
test('Cross-midnight Start cutoff is on previous calendar day',()=>{const t=pickup({completeAfter:localTime('2026-09-11',0,30),completeBefore:localTime('2026-09-11',0,30)});assert.equal(checkTask(t,{now:at(23,30),selectedDate:'2026-09-11'}).flags[0].kind,'NOT_STARTED');assert.equal(checkTask(t,{now:at(23,29),selectedDate:'2026-09-11'}).status,'SCHEDULED');});
test('Toronto day differs from UTC near midnight',()=>assert.equal(dayAt(Date.parse('2026-09-11T02:00:00Z')),day));
test('Spring DST day is 23 hours',()=>assert.equal(localTime('2026-03-09')-localTime('2026-03-08'),23*3600000));
test('Autumn DST day is 25 hours',()=>assert.equal(localTime('2026-11-02')-localTime('2026-11-01'),25*3600000));
test('Nonexistent DST local time is not silently normalized',()=>assert.equal(localTime('2026-03-08',2,30),null));
test('Calendar validation rejects invalid and non ISO dates',()=>{assert.equal(validDay('2026-02-30'),false);assert.equal(validDay('09/10/2026'),false);assert.equal(validDay('2026-09-10'),true);});
test('Date increment crosses year',()=>assert.equal(shiftDay('2026-12-31',1),'2027-01-01'));
test('Second timestamps are not guessed as milliseconds',()=>assert.equal(timestamp(1789052400),null));
test('Predicted late is AT_RISK before actual deadline',()=>assert.equal(check(pickup({state:2,eta:3700})).status,'AT_RISK'));
test('Task becomes actually late only after deadline',()=>assert.equal(check(pickup({state:2}),at(11,1)).status,'LATE'));
test('Valid generous ETA supports on-time',()=>assert.equal(check(pickup({state:2,eta:1200})).status,'ON_TIME'));
test('No ETA never defaults to on-time',()=>assert.equal(check(pickup({state:2})).status,'UNKNOWN'));
test('Stale estimate cannot prove on-time',()=>assert.equal(check(pickup({state:2,estimatedCompletionTime:at(9)})).status,'UNKNOWN'));
test('Worker delay cannot turn tomorrow-only driver late',()=>{const t=pickup({completeAfter:localTime('2026-09-11',11),completeBefore:localTime('2026-09-11',11)});const s=makeSnapshot({workers:[worker({delayTime:999})],tasks:[t],date:day,now:at(10)});assert.equal(s.drivers[0].status,'NO_TASKS');});
test('No jobs is NO_TASKS, not ON_TIME',()=>assert.equal(makeSnapshot({workers:[worker()],date:day,now:at(10)}).drivers[0].status,'NO_TASKS'));
test('Partial source never presents all-clear',()=>assert.equal(makeSnapshot({workers:[worker()],date:day,complete:false,now:at(10)}).drivers[0].status,'UNKNOWN'));
test('Partial source preserves positively known late issue',()=>assert.equal(makeSnapshot({workers:[worker()],tasks:[pickup()],date:day,complete:false,now:at(11,2)}).drivers[0].status,'LATE'));
test('Off duty does not hide late task',()=>{const s=makeSnapshot({workers:[worker({onDuty:false})],tasks:[pickup()],date:day,now:at(11,2)});assert.equal(s.drivers[0].status,'LATE');assert.equal(s.drivers[0].online,false);});
test('Completed late remains post-audit, not driver current LATE',()=>{const t=pickup({state:3,completionDetails:{success:true,time:at(11,10)}});const s=makeSnapshot({workers:[worker()],tasks:[t],date:day,now:at(12)});assert.equal(s.tasks[0].status,'COMPLETED_LATE');assert.equal(s.drivers[0].status,'DONE');});
test('Completed failure is not on-time',()=>assert.equal(check(pickup({state:3,completionDetails:{success:false,time:at(11)}}),at(12)).status,'FAILED'));
test('Invalid schedule excluded with data warning',()=>{const s=makeSnapshot({tasks:[pickup({completeAfter:at(12)})],date:day,now:at(12)});assert.equal(s.tasks.length,0);assert.ok(s.warnings.length);});
const active=pickup({state:2,destination:{location:[-79.1,43.5]}});
const point=(min,location=[-79.4,43.7])=>({at:at(10,min),seen:at(10,min),location,taskId:'pickup1'});
test('Start state is not evidence of movement',()=>assert.equal(motion(worker(),active,[],at(10,15)),'CHECKING'));
test('Stale GPS is unknown, not stationary',()=>assert.equal(motion(worker({timeLastSeen:at(10)}),active,[],at(10,15)),'GPS_STALE'));
test('Near destination suppresses false stationary alert',()=>assert.equal(motion(worker(),{...active,destination:{location:[-79.4,43.7]}},[],at(10,15)),'AT_STOP'));
test('GPS displacement establishes movement',()=>assert.equal(motion(worker({location:[-79.397,43.7]}),active,[point(14),point(15,[-79.397,43.7])],at(10,15)),'MOVING'));
test('10 minutes fresh continuous static GPS is possible stop',()=>assert.equal(motion(worker(),active,Array.from({length:11},(_,i)=>point(5+i)),at(10,15)),'STATIONARY'));
test('Short static observation is not enough',()=>assert.equal(motion(worker(),active,[point(14),point(15)],at(10,15)),'CHECKING'));
test('Observation gaps suppress stationary inference',()=>assert.equal(motion(worker(),active,[point(0),point(1),point(2),point(13),point(14),point(15)],at(10,15)),'CHECKING'));
test('History resets when driver starts a different task',()=>assert.equal(addSamples({driver1:[point(14)]},[worker({activeTask:'new-task'})],at(10,15)).driver1.length,1));
test('Sheet dirty time formats parse conservatively',()=>{for(const v of ['10:30 AM','10.30am','1030am'])assert.equal(parseWindow(v,day).start,at(10,30));assert.equal(parseWindow('4 - 4:30 PM',day).end,at(16,30));assert.equal(parseWindow('11:45 AM - 12 PM',day).end,at(12));assert.equal(parseWindow('TBD',day),null);});
test('Sheet row parser uses exact header roles, not restaurant as driver',()=>{const result=normalizeRows([['Notes','Providor','workerName','ONFLEET ID','Order Date','Pickup Time','Client Delivery Time'],['x','Vendor','Restaurant','abcd1234','Thu Sep 10','11:00 AM','11:30 AM']],day);assert.equal(result.rows[0].pickupAt,at(11));assert.equal(result.rows[0].driver,undefined);});
test('Blank Sheet ID is mapping review, not missing',()=>assert.equal(matchRows([{date:day,onfleetId:'',validId:false}],[],true)[0].status,'NEEDS_ID'));
test('Duplicate Sheet IDs need review, not automatic deletion',()=>{const rows=[1,2].map(row=>({row,date:day,onfleetId:'abcd1234',validId:true}));assert.ok(matchRows(rows,[pickup()],true).every(r=>r.status==='AMBIGUOUS'));});
test('Partial Onfleet read disables missing conclusions',()=>assert.equal(matchRows([{date:day,onfleetId:'abcd1234',validId:true}],[],false)[0].status,'UNVERIFIED'));
test('Exact ID matching distinguishes wrong date',()=>assert.equal(matchRows([{date:'2026-09-11',onfleetId:'abcd1234',validId:true}],[pickup()])[0].status,'DATE_MISMATCH'));
test('Sheet cutoff can override only verified pickup link',()=>{const r={status:'MATCHED',taskId:'pickup1',date:day,pickupAt:at(12),row:2};const p=sheetPlans([r],[pickup()]);assert.equal(checkTask(pickup(),{now:at(10),selectedDate:day,plan:p.plans[0]}).status,'SCHEDULED');assert.ok(p.notes.length);});
test('Sheet delivery with ambiguous pickups does not start wrong task',()=>{const d={...pickup(),id:'drop',pickupTask:false,dependencies:['pickup1','pickup2']};const p=sheetPlans([{status:'MATCHED',taskId:'drop',date:day,pickupAt:at(11),deliveryAt:at(12),row:2}],[d,pickup(),pickup({id:'pickup2'})]);assert.equal(p.plans.filter(x=>x.pickupAt).length,0);assert.ok(p.notes.length);});
test('Empty pagination page still follows lastId',async()=>{let calls=0;const r=await readPages({from:'0'},async path=>{calls++;if(calls===1)return {tasks:[],lastId:'cursor'};assert.match(path,/lastId=cursor/);return {tasks:[pickup()]};});assert.equal(r.complete,true);assert.equal(calls,2);assert.equal(r.tasks.length,1);});
test('Pagination truncation stays incomplete',async()=>assert.equal((await readPages({},async()=>({tasks:[],lastId:'more'}),{maxPages:1})).complete,false));
test('Pagination repeated cursor fails rather than returns healthy',async()=>assert.rejects(()=>readPages({},async()=>({tasks:[],lastId:'again'})),/repeated/));
test('Live adapter uses bounded recent task scan rather than from=0',async()=>{const paths=[];await getOnfleet(day,{useCache:false,now:at(10),request:async path=>{paths.push(path);return path.startsWith('/workers')?[]:{tasks:[]};}});assert.ok(paths.some(p=>p.startsWith('/tasks/all?')&&!p.includes('from=0')&&p.includes('state=0%2C1%2C2')));});
test('Provider error is not swallowed',async()=>assert.rejects(()=>getOnfleet(day,{useCache:false,request:async()=>{throw new Error('429');}}),/429/));
const warning={id:'cutoff:1',kind:'NOT_STARTED',severity:'WATCH',dueAt:at(10)};
test('Future due alert does not send early',()=>assert.equal(notificationPlan([warning],{},at(9,59)).due.length,0));
test('Same alert stage deduplicates per device',()=>{const p=notificationPlan([warning],{},at(10));p.due[0].entry.receipts.phone=p.due[0].key;const next=notificationPlan([warning],p.ledger,at(10,1));assert.equal(next.due[0].key,next.due[0].entry.receipts.phone);});
test('Escalates at 15 and 30 then stops repeating',()=>{const p=notificationPlan([warning],{},at(10));const a=notificationPlan([warning],p.ledger,at(10,15));const b=notificationPlan([warning],a.ledger,at(10,30));const c=notificationPlan([warning],b.ledger,at(11));assert.notEqual(p.due[0].key,a.due[0].key);assert.notEqual(a.due[0].key,b.due[0].key);assert.equal(b.due[0].key,c.due[0].key);});
test('Resolved alert can reopen as new occurrence',()=>{const p=notificationPlan([warning],{},at(10));const closed=notificationPlan([],p.ledger,at(10,2));const reopened=notificationPlan([warning],closed.ledger,at(10,3));assert.notEqual(p.due[0].key,reopened.due[0].key);});
test('Failed partial scan does not resolve previous issues',()=>{const p=notificationPlan([warning],{},at(10));const next=notificationPlan([],p.ledger,at(10,1),false);assert.equal(next.ledger[warning.id].resolvedAt,null);});
test('Push endpoint SSRF guard blocks localhost',()=>assert.throws(()=>validateSubscription({endpoint:'https://127.0.0.1/internal'}),/allowed/));
test('Push endpoint rejects credentials on allowed host',()=>assert.throws(()=>validateSubscription({endpoint:'https://user:pass@fcm.googleapis.com/x'}),/allowed/));
test('Push accepts well-formed Apple web push subscription',()=>assert.ok(validateSubscription({endpoint:'https://web.push.apple.com/Qtest',keys:{p256dh:Buffer.alloc(65).toString('base64url'),auth:Buffer.alloc(16).toString('base64url')}})));
test('Auth is fail closed if no configured password',()=>{const old=process.env.APP_ACCESS_PASSWORD;delete process.env.APP_ACCESS_PASSWORD;try{assert.throws(()=>authorized({headers:{}}),/SETUP_REQUIRED/);}finally{if(old)process.env.APP_ACCESS_PASSWORD=old;}});
test('Session expires and signature prevents modification',()=>{process.env.APP_ACCESS_PASSWORD='test-only-not-for-production-123';const token=makeSession(at(10));assert.equal(authorized({headers:{cookie:'ss_dispatch='+token}},at(11)),true);assert.equal(authorized({headers:{cookie:'ss_dispatch='+token}},at(23)),false);assert.equal(authorized({headers:{cookie:'ss_dispatch='+token+'x'}},at(11)),false);delete process.env.APP_ACCESS_PASSWORD;});
test('CSRF rejects foreign origins',()=>{let code=0;const res={status(n){code=n;return this;},json(){}};assert.equal(requireOrigin({headers:{host:'app.example.com',origin:'https://evil.example.com'}},res),false);assert.equal(code,403);});
