import {createHash,createHmac,timingSafeEqual,randomUUID} from 'node:crypto';
export function same(a,b) {return timingSafeEqual(createHash('sha256').update(String(a)).digest(),createHash('sha256').update(String(b)).digest());}
function secret(){const s=process.env.APP_ACCESS_PASSWORD;if(!s||s.length<16)throw new Error('SETUP_REQUIRED: Set APP_ACCESS_PASSWORD to a random password of at least 16 characters in Vercel.');return s;}
export function cookieValue(req,name) {return (req.headers?.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(`${name}=`))?.slice(name.length+1)||'';}
export function makeSession(now=Date.now()) {const data=Buffer.from(JSON.stringify({exp:now+12*3600000,id:randomUUID()})).toString('base64url');return `${data}.${createHmac('sha256',secret()).update(data).digest('base64url')}`;}
export function authorized(req,now=Date.now()) {const s=secret();const token=cookieValue(req,'ss_dispatch'),[data,sig,...rest]=token.split('.');if(!data||!sig||rest.length)return false;const expected=createHmac('sha256',s).update(data).digest('base64url');if(!same(sig,expected))return false;try{const p=JSON.parse(Buffer.from(data,'base64url').toString());return Number.isFinite(p.exp)&&p.exp>now&&p.exp<=now+12*3600000;}catch{return false;}}
export function safeHeaders(res) {res.setHeader('Cache-Control','private, no-store, max-age=0');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');}
export function requireAuth(req,res) {safeHeaders(res);try{if(authorized(req))return true;res.status(401).json({connected:false,error:'Please sign in.'});}catch{res.status(503).json({connected:false,error:'SETUP_REQUIRED: Add APP_ACCESS_PASSWORD (16+ random characters) in Vercel, then redeploy.'});}return false;}
export function requireOrigin(req,res) {const origin=req.headers?.origin;const host=req.headers?.host;if(!origin||!host){res.status(403).json({error:'Same-origin request required.'});return false;}try{if(new URL(origin).host===host)return true;}catch{}res.status(403).json({error:'Origin rejected.'});return false;}
export async function jsonBody(req) {if(!String(req.headers?.['content-type']||'').includes('application/json'))throw new Error('JSON required');if(typeof req.body==='object'&&req.body!==null){if(JSON.stringify(req.body).length>10000)throw new Error('Body too large');return req.body;}if(typeof req.body==='string'){if(req.body.length>10000)throw new Error('Body too large');return JSON.parse(req.body);}let text='';for await(const chunk of req){text+=chunk;if(text.length>10000)throw new Error('Body too large');}return JSON.parse(text);}
